### ISSUE TITLE
Invalid syntax for alternative repository. Use "id::layout::url"

### ISSUE THREAD

**Issue by bigfacewo** [simontunnat/action-maven-deploy#2]
action-maven-deploy version:1.1
maven version: 3.5.4
java version: 8

The action command is as follows:
```
/home/github/_work/_tool/maven/3.5.4/x64/bin/mvn -B clean deploy --settings /tmp/action-maven-deploy-settings.xml -DaltDeploymentRepository=action-maven-deploy::http://192.168.100.106:30100/repository/maven-public/
```
The following error is reported when executing deploy:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project uniplore-commons: Invalid syntax for repository. Invalid syntax for repository. 
Error:  Invalid syntax for alternative repository. Use "id::layout::url".
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error: The process '/home/github/_work/_tool/maven/3.5.4/x64/bin/mvn' failed with exit code 1
```

Is there something wrong with me?

**Comment by simontunnat** [comment]
This seems to be an issue with older versions of the maven-deploy-plugin. For my last deployment I was using version 3.0.0-M1.

> Note: Since 3.0.0 the layout part has been removed.
> https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html

Can you confirm this? Then I will add some notice about this to the README.

**Comment by bigfacewo** [comment]
I'm not sure what version I'm using. i just configure `spring-boot-maven-plugin:2.2.10.RELEASE` and `docker-maven-plugin:1.2.2`.
I searched `maven-deploy-plugin` globally and found 2.7 and 2.8.2.
But you are right.
Thanks!
